FROM gradle:7.4.1-jdk17-alpine as build
WORKDIR /app
COPY ./ ./
RUN gradle clean assemble --info


FROM gradle:7.4.1-jdk17-alpine as main
ARG app_name
WORKDIR /app
COPY --from=build /app/$app_name/build/libs/$app_name-0.0.1-SNAPSHOT.jar ./app.jar
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=prod,redis"]




