FROM node:18.7.0-slim as build
WORKDIR /app
COPY ./ui/package.json ./
RUN npm install
COPY ./ui/ ./
RUN npm run build


FROM nginx:1.23-alpine
COPY ./ui/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build app/build/ /usr/share/nginx/html
ENTRYPOINT ["nginx", "-g", "daemon off;"]