version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  check:
    desc: Verify local tools
    cmds:
      - docker --info
      - java --version
      - gradlew --help

  infra:
    desc: Spin up dockerized infrastructure (postgres db)
    cmds:
      - docker-compose up -d redis
      - docker run --rm -it --network food-delivery-redis_default redis redis-cli -h redis FT.CREATE food-idx ON JSON PREFIX 1 "food:" SCHEMA $.name AS name TEXT

  run:
    desc: Run all services in Docker
    cmds:
      - task: infra
      - docker-compose up -d bff ordering delivery food ui

  init:
    desc: Run all services in Docker for the 1st time
    cmds:
      - task: run
      - bash init-data.sh

  local:
    desc: Run backend apps with gradle
    cmds:
      - task: infra
      - echo "Starting food-delivery app..."
      - gradlew clean assemble --info
      - gradlew --parallel startBootStack --info

  infra-down:
    desc: Stop infrastructure
    cmds:
      - docker-compose down --rmi
      - echo "All infra apps stopped."

  infra-clean:
    desc: Stop and clean all persisted data
    cmds:
      - task: infra-down
      - docker volume rm food-delivery-redis_redis-data
      - echo "Docker volumes cleaned."
